server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 975757054220-6udbrkoujugh44g6teogbc1bbfdadqc0.apps.googleusercontent.com
            client-secret: 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
            scope: [openid, profile, email]
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            issuer-uri: https://accounts.google.com

# Allow your frontend dev URL
app:
  frontend-url: http://localhost:5173
  jwt:
    issuer: demo-auth
    access-token-minutes: 120